text1 = input("text1")
text2 = input("text2")
print(f'Je prvni text delsi? {len(text1) > len(text2)}')
print(f'Jak je dlouhy text1: {len(text1)}')
print(f'kolik pismen ma text2: {len(text2)}')
print(f'kolikate pismeno')
